Add documentation for 'assetLineageTopicConnectionOverride'
odpi/egeria-docs pull request #629
Opened 2022-12-13 12:33 UTC by popa-raluca

Signed-off-by: Raluca Popa <raluca.popa2@ing.com>

2022-12-13 13:23 UTC, mandy-chessell requested changes

2022-12-13 13:23 UTC, mandy-chessell commented on site/docs/guides/admin/servers/configuring-an-open-lineage-server.md
> +`assetLineageTopicConnectionOverride` | Configuraton oject that provides the Asset Lineage OMAS kafka topic properties. If provided, it will override the default configuraiton  | No |
Spelling mistakes: `Configuration` (x2) and `object`

`Configuration object` should probably be `[Connection object](/concepts/connection)`

2022-12-13 13:23 UTC, mandy-chessell commented on site/docs/guides/admin/servers/configuring-an-open-lineage-server.md
> +        "assetLineageTopicConnectionOverride": {
This is not a valid connection object.  

It *must* have a connector type that indicates the type of connector to connect.  
It should have an endpoint to point to the location to connect to.

2022-12-19 09:03 UTC, lpalashevski requested changes
If we can simplify the inTopic connection configuration to only have required bean properties

2022-12-19 12:37 UTC, lpalashevski approved these changes

2022-12-20 09:44 UTC, lpalashevski approved these changes

2022-12-20 10:04 UTC, merged