Add initial docs on k8s healthchecks
odpi/egeria-docs pull request #775
Opened 2023-05-18 17:32 UTC by planetf1

Draft doc on api healthchecks

2023-06-29 09:54 UTC, planetf1 commented
Hopefully this doc contribution is useful - if it looks ok, please consider merging :-)

2023-06-29 10:11 UTC, mandy-chessell requested changes
Useful content - just need to correct calls away from deprecated REST API calls.

2023-06-29 10:11 UTC, mandy-chessell commented on site/docs/guides/operations/kubernetes/healthchecks.md
> +#### Platform is not running
This call is deprecated.  Should be `https://44623abc-eu-gb.lb.appdomain.cloud:9443/open-metadata/platform-services/users/admin/server-platform/origin`

2023-06-29 10:11 UTC, mandy-chessell commented on site/docs/guides/operations/kubernetes/healthchecks.md
> +Egeria OMAG Server Platform (version 4.1-SNAPSHOT)
I am not sure how the platform returns a version if it is not running.

2023-06-29 10:11 UTC, mandy-chessell commented on site/docs/guides/operations/kubernetes/healthchecks.md
> +➜  ~ http --verify=no --pretty=format GET "https://44623abc-eu-gb.lb.appdomain.cloud:9443/open-metadata/admin-services/users/admin/server-origin"
Again - deprecated request

2023-06-29 10:11 UTC, mandy-chessell commented on site/docs/guides/operations/kubernetes/healthchecks.md
> +```
This call indicates whether the server is running or not - the call to determine whether the server is known on the platform is `{baseURL}/open-metadata/platform-services/users/{user}/server-platform/servers/{serverName}/is-known`

2023-06-29 10:11 UTC, mandy-chessell commented on site/docs/guides/operations/kubernetes/healthchecks.md
> +➜  ~ http --verify=no --pretty=format GET "https://44623abc-eu-gb.lb.appdomain.cloud:9443/open-metadata/admin-services/users/admin/servers/cocoMDS5/instance/status"
This call is deprecated - should use the platform services request ` {baseURL}/open-metadata/platform-services/users/{user}/server-platform/servers/{serverName}/instance/status`

2023-06-29 10:11 UTC, mandy-chessell commented on site/docs/guides/operations/kubernetes/healthchecks.md
> +```
There is also a simpler call to test if the server is active ... `{baseURL}/open-metadata/platform-services/users/{user}/server-platform/servers/{serverName}/is-active`

2023-06-29 10:11 UTC, mandy-chessell commented on site/docs/guides/operations/kubernetes/healthchecks.md
> +curl -k -o - -X GET --connect-timeout 5 --max-time 5 "https://44623abc-eu-gb.lb.appdomain.cloud:9443/open-metadata/admin-services/users/admin/servers/cocoMDS5/instance/status" | grep '.*\"relatedHTTP
Update for latest request

2023-06-29 10:26 UTC, planetf1 commented
Thanks for the review comments. will try and propose an update

2026-08-31 19:54 UTC, mandy-chessell commented
These are all on pages we no longer have in the site

2026-08-31 19:54 UTC, closed without merging